services:
  next:
    build:
      context: .
      target: next
    env_file:
      - .env
    ports:
      - "3005:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next.rule=Host(`partiel.sutcorp-industry.com`)"
      - "traefik.http.routers.next.entrypoints=websecure"
      - "traefik.http.routers.next.tls.certresolver=myresolver"
      - "traefik.http.services.next.loadbalancer.server.port=3000"
    networks:
      - frontend
      - coolify
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: conference_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frontend

volumes:
  postgres_data:

networks:
  frontend:
    driver: bridge
  coolify:
    external: true 